'''Write a  Python program to create a dictionary with the same keys as the given dictionary and values generated by running the given function for each value.
Sample Output:
Original dictionary elements:
{'Theodore': {'user': 'Theodore', 'age': 45}, 'Roxanne': {'user': 'Roxanne', 'age': 15}, 'Mathew': {'user': 'Mathew', 'age': 21}}
Dictionary with the same keys:
{'Theodore': 45, 'Roxanne': 15, 'Mathew': 21}'''


def generate_values(data, func):
    return {key: func(value) for key, value in data.items()}

original_dict = {
    'Theodore': {'user': 'Theodore', 'age': 45},
    'Roxanne': {'user': 'Roxanne', 'age': 15},
    'Mathew': {'user': 'Mathew', 'age': 21}
}

def extract_age(data):
    return data['age']

result = generate_values(original_dict, extract_age)

print("Original dictionary elements:")
print(original_dict)
print("Dictionary with the same keys:")
print(result)
